spring:
  main:
    web-application-type: reactive
  config:
    import: optional:env/env.properties
  cloud:
      gateway:
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
              allowCredentials: true
        routes:
            - id: gamedataservice
              uri: http://localhost:8082
              predicates:
                  - Path=/api/gamedata/**
              filters:
                - RewritePath=/api/gamedata/(?<segment>.*), /api/gamedataservice/$\{segment}

            - id: authservice
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
              filters:
                - RewritePath=/api/auth/(?<segment>.*), /api/authservice/$\{segment}

leagueapi:
  gateway:
    paths-without-authentication: /api/auth/authentication/authenticate, /api/auth/authentication/signup

jwt:
  key:
    secret: ${SECRET:#{null}}
    signature: BeqbvWM1mem/MP887bU919s3AAQmFl6cdanzq5h7LZof9Cz2XsQcAXGuqGziW6t0zAkoB6bevoj/JYN/4sIPjWKoibQr3YsigC4Fiip6CN0=

server:
    port: 8080

logging:
  level:
    root: debug
